### ISSUE TITLE
Lables usage and documentation is missing

### ISSUE THREAD

**Issue by glensc** [laminas/automatic-releases#107]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes/no
| BC Break    | yes/no

#### Summary

The release generation process seems to use labels somehow:
- https://github.com/laminas/laminas-mail/releases/tag/2.13.0

The changelog items seem to be categorized by the labels:

```
Bug
129: Tests: Resolve duplicate data provider key thanks to @glensc
125: Merge release 2.12.5 into 2.13.x thanks to @github-actions[bot]

Duplicate,Enhancement
127: phpunit9 and php8 thanks to @delboy1978uk

Enhancement
117: Add PHP 8.0 support thanks to @bfoosness
109: Code style fixes in tests thanks to @glensc
101: Fixes #34 replace call_user_func* with self invoked function thanks to @samsonasik
34: replace call_user_func* with self invoked function thanks to @michalbundyra
```

I checked [README.md](https://github.com/laminas/automatic-releases/blob/1.9.1/README.md) and found no match for labels being documented.

**Comment by Ocramius** [comment]
Yes, that is how the underlying dependency generating the changelog, [`jwage/changelog-generator`](https://github.com/jwage/changelog-generator) generates the changelog text.
