### ISSUE TITLE
Add mechanism to automatically switch active branch on a new minor or major release

### ISSUE THREAD

**Issue by Ocramius** [laminas/automatic-releases#11]
As discussed in the @laminas/technical-steering-committee meeting, we want to move away from the `master` branch naming, towards a more user-friendly naming scheme that exposes version names.

The idea is that whenever a `x.y.0` or `x.0.0` release is tagged, the tool will automatically switch to that release's branch, if it is the latest.

### New minor

For example, given following branches:

 * `1.0.x`
 * `1.1.x` marked as **default** 

When `1.2.0` is tagged, we should see:

 * `1.0.x`
 * `1.1.x`
 * `1.2.x` marked as **default** 

### New major

For example, given following branches:

 * `1.0.x`
 * `1.1.x`
 * `1.2.x` marked as **default** 

When `2.0.0` is tagged, we should see:

 * `1.0.x`
 * `1.1.x`
 * `1.2.x`
 * `2.0.x` marked as **default**

**Comment by weierophinney** [comment]
This raises a question: if the last release was 1.1.x, and the default branch is now 1.2.x but does not have any releases against it yet, how do we signal that the next release will be 2.0.0, and not 1.2.0? That's the main reason I can see for having a non-version-named branch as the default: to allow us to decide later what the target will be.

**Comment by Ocramius** [comment]
> how do we signal that the next release will be 2.0.0, and not 1.2.0?

That's up to the maintainer to create.

I'm almost through an initial implementation, and I think that a healthy default for this tool is to create the `x.{y+1}.0` branch by default, and to leave `{x+1}.0.0` alone.

From a maintainer perspective, a new major branch can be created at any time.

Patch will be up shortly: we can probably discuss things there while reviewing.

**Comment by Ocramius** [comment]
@weierophinney #12 implements this feature in a superficial way.
