### ISSUE TITLE
Add branch protection to release branches

### ISSUE THREAD

**Issue by Slamdunk** [laminas/automatic-releases#126]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | no

#### Summary

Hi, I'd love to have [branch protection](https://docs.github.com/en/github/administering-a-repository/about-protected-branches) (here's the [API](https://docs.github.com/en/rest/reference/repos#update-branch-protection)) automatically added for release branches created by this action.

There are many options and we could provide a `1:1` config-to-API environment variables, but we could start with a basic on/off one for the destruction-protective ones:

```json
{
  "allow_force_pushes": false,
  "allow_deletions": false
}
```

**Comment by Ocramius** [comment]
deletions are IMO valid on stable branches: they go EOL at some point.

Fully agree on force-push protection :+1: 

Does github allow passing flags when doing a `git push`?

**Comment by Slamdunk** [comment]
> deletions are IMO valid on stable branches: they go EOL at some point.

Ok, so this action needs to also delete the corresponding branch protection rule upon branch deletion, so rules don't add up to infinity.

> Does github allow passing flags when doing a `git push`?

Have no idea what you are asking here.
This API needs the same auth as `Github\Api\V3\SetDefaultBranch`, which is called in [`SwitchDefaultBranchToNextMinor`](https://github.com/laminas/automatic-releases/blob/1.11.x/src/Application/Command/SwitchDefaultBranchToNextMinor.php#L89), what's the meaning of `git push` here?

`ORGANIZATION_ADMIN_TOKEN` is mandatory, if you are asking.

**Comment by glensc** [comment]
`git push -o` need's GitHub server-side support, here's list of what gitlab has implemented:
- https://docs.gitlab.com/ee/user/project/push_options.html

**Comment by Ocramius** [comment]
I just realized that setting up branch protections is as simple as putting a rule on `*.*.x` (github does not support more advanced regular expressions, afaik).

Given that, I don't think this should be implemented here, since a `*.*.x` rule can already be created to:

 * prevent force-pushing
 * prevent deletion

**Comment by Slamdunk** [comment]
I knew `*.*.x` from the beginning, but considered too much cuz I'd like deletion prevention, but also be able to delete EOLed branches.

I'm ok with `*.*.x` and force-push prevention only, though. YOLO

**Comment by Ocramius** [comment]
Eh, can delete branches during a maintenance time window when the rule is
disabled/removed temporarily 😬
