### ISSUE TITLE
Will this work with RC, beta or alpha versions

### ISSUE THREAD

**Issue by svycka** [laminas/automatic-releases#15]
and also with 0.y.x versions?

**Comment by Ocramius** [comment]
For `0.x.y` versions, I have written unit tests, but haven't tried it.

RC, beta and alpha are **NOT** going to work with the current codebase.

Note: the observable effect for RC, beta and alpha will be a github action crash.

**Comment by svycka** [comment]
as I remember laminas does not use RC, alpha, and beta but sometimes uses 0.y.z so it's nice if this works

**Comment by Ocramius** [comment]
Alpha, Beta and RC can still be done manually, but indeed, if there's a need for it, the tooling can be improved.
