### ISSUE TITLE
Display command output on failure

### ISSUE THREAD

**Issue by greg0ire** [laminas/automatic-releases#166]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

Right now, potentially helpful output of external programs is not displayed on error, making it hard to troubleshoot them: https://github.com/doctrine/orm/runs/3782157355?check_suite_focus=true#step:4:18

I can think of 2 solutions:
- catch the exception, and wrap it with another that includes the result of `$e->getOutput()` and `$e->getErrorOutput()`
- file an issue on azjezz/psl so that the output is included in the exception's error message.

Cc @azjezz

**Comment by azjezz** [comment]
> file an issue on azjezz/psl so that the output is included in the exception's error message.

If you think that's a good idea, we can do it, i don't think it would count as a BC break 🤔 

The reason i didn't do it initially is that it could result in a messy output + it might expose information that you do not want to be exposed ( especially when used in a web app and you don't have a proper error handler configured )

**Comment by greg0ire** [comment]
I think that's a good idea yes! Having it configurable for security-concerned people would be a plus!
