### ISSUE TITLE
Fix release markdown rendering of double newlines

### ISSUE THREAD

**Issue by glensc** [laminas/automatic-releases#176]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | [v1](https://github.com/perftools/xhgui/blob/0.19.1/.github/workflows/release-on-milestone-closed.yml#L31)

#### Summary

Because there's a double newline between two lists, markdown renders every item with double newlines and considers the two lists as one.

The workaround is to put some non-list element between the lists.

#### Current behavior

![image](https://user-images.githubusercontent.com/199095/149661572-18844838-ef8e-4bde-8715-916adaca538c.png)

<details>

<summary>markdown source</summary>

```
### Release Notes for [0.19.1](https://github.com/perftools/xhgui/milestone/19)

0.19.x bugfix release (patch)

### 0.19.1

- Total issues resolved: **0**
- Total pull requests resolved: **4**
- Total contributors: **2**

 - [442: Cleanup:  Remove adding ext-phar for build in Dockerfile](https://github.com/perftools/xhgui/pull/442) thanks to @glensc
 - [441: Set GIT&#95;AUTHOR&#95;NAME/GIT&#95;AUTHOR&#95;EMAIL via env rather secrets](https://github.com/perftools/xhgui/pull/441) thanks to @glensc
 - [438: Feature: Add driver name to PdoRepository](https://github.com/perftools/xhgui/pull/438) thanks to @glensc
 - [436: Implement pdo: getForUrl(), getPercentileForUrl(), getAll()](https://github.com/perftools/xhgui/pull/436) thanks to @fengqi

```
</details>

#### Expected behavior

![image](https://user-images.githubusercontent.com/199095/149661645-4504bd1c-6fe7-423a-9e48-31e98e3524b5.png)

<details>

<summary>markdown source</summary>

```
### Release Notes for [0.19.1](https://github.com/perftools/xhgui/milestone/19)

0.19.x bugfix release (patch)

### 0.19.1

Summary:
- Total issues resolved: **0**
- Total pull requests resolved: **4**
- Total contributors: **2**

Pull requests:
 - [442: Cleanup:  Remove adding ext-phar for build in Dockerfile](https://github.com/perftools/xhgui/pull/442) thanks to @glensc
 - [441: Set GIT&#95;AUTHOR&#95;NAME/GIT&#95;AUTHOR&#95;EMAIL via env rather secrets](https://github.com/perftools/xhgui/pull/441) thanks to @glensc
 - [438: Feature: Add driver name to PdoRepository](https://github.com/perftools/xhgui/pull/438) thanks to @glensc
 - [436: Implement pdo: getForUrl(), getPercentileForUrl(), getAll()](https://github.com/perftools/xhgui/pull/436) thanks to @fengqi

```
</details>

**Comment by glensc** [comment]
If you don't want to make changes to markdown formatting, is there a way to customize this in project I use?

**Comment by Ocramius** [comment]
IIRC, the markdown is generated by https://github.com/jwage/changelog-generator

To customize the release text, you would implement `CreateReleaseText` yourself:

https://github.com/laminas/automatic-releases/blob/41da24928d936a3cd950ac851c24b559debac1e1/src/Github/CreateReleaseText.php#L13-L34

Then inject it in the command:

https://github.com/laminas/automatic-releases/blob/41da24928d936a3cd950ac851c24b559debac1e1/src/Application/Command/ReleaseCommand.php#L37-L61

This is probably best done by having your own `bin/console` replacement:

https://github.com/laminas/automatic-releases/blob/41da24928d936a3cd950ac851c24b559debac1e1/bin/console.php#L53-L172

Note how `bin/console` is really just doing some DI setup :)

**Comment by glensc** [comment]
I was hoping of configuration via:
1. env variables
2. "with:" action paramters
3. command-line arguments

not forking code and ecosystem around it 🗡️ 

but, have you though of having a container to define dependencies, like:
- https://github.com/perftools/xhgui/blob/44d856ab70ad8066e22266a765253a502c782373/src/ServiceProvider/MongoStorageProvider.php#L27-L35

so, I could provide my override container if just want to wiggle few bits.

**Comment by Ocramius** [comment]
Potentially feasible, but this application was never designed for customization, rather quick iteration and ease of use (which is quite a challenge already, given the GPG requirements).

IMO forking + customizing is the way to go here, as it is not a library, but an application.

If I can get rid of a config setting, and instead make it a default, I'll gladly do that instead.

**Comment by Ocramius** [comment]
Very similar/related: https://github.com/Roave/BackwardCompatibilityCheck/issues/377

In fact, `bin/console` is the only thing to replace.

**Comment by glensc** [comment]
but that's replacing whole bin/console content... instead of just overriding single thing: $container->set(SOMEDEPENDENCY, SOMETHINGELSE)

**Comment by Ocramius** [comment]
Yes, and that's no big deal, especially if you just need one of the many commands.

It is intentional/by design.

EDIT: in fact, give it a shot - if all you need is a single command to override, writing your own little script that uses symbols from this library should be enough, and quicker to write/easier to maintain than actually inventing a configuration DSL.

**Comment by WyriHaximus** [comment]
@Ocramius Will this do? https://github.com/jwage/changelog-generator/pull/71

**Comment by Ocramius** [comment]
Most likely, ya - not sure about the difference in output between grouped/non-grouped: the tests are quite hard to read

**Comment by WyriHaximus** [comment]
The only thing non-grouped will do is set that label to anything without a group. Will improve the wording, also not sure if non-grouped is the right term here 🤐
