### ISSUE TITLE
Major version tag `v1` for action reference

### ISSUE THREAD

**Issue by geerteltink** [laminas/automatic-releases#34]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | sort of

#### Summary

As a user I want to use the latest stable action without having to update my github action scripts all the time. GitHub suggest to create a v1 tag that will follow the latest 1.x release.

e.g. the current example script still points to `laminas/automatic-releases@1.0.1` while `1.1.0` is out. 

By using `v1` tags which follow the latest stable release, you can use something like this, `laminas/automatic-releases@v1`.

https://docs.github.com/en/actions/creating-actions/about-actions#using-tags-for-release-management

I think this is also useful for all laminas and mezzio packages. As we manually "move" the `v1` tag, we can decide when we are happy with a specific stable release and move the `v1` tag so all components will start using it.

**Comment by weierophinney** [comment]
v1 tag is now created. I'm going to look for a github action that can automate this, though, before I close it.
