### ISSUE TITLE
Does not checkout release branch before attempting to update changelog

### ISSUE THREAD

**Issue by weierophinney** [laminas/automatic-releases#46]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.2.1

#### Summary

The `laminas:automatic-releases:release` command fails when attempting to commit the release date to the `CHANGELOG.md` file when the default branch is other than the release branch.

As a specific example: I recently attempted to close milestone 2.12.3 of laminas-mail. A 2.13.x branch already exists. When it attempted to push changes for the changelog, I received the error here: https://github.com/laminas/laminas-mail/runs/977187215?check_suite_focus=true#step:4:14

#### How to reproduce

Create a release branch "X.Y.x", and another "X.Y+1.x". Close a milestone related to "X.Y.x".

#### Expected behavior

It should check out the associated release branch prior to updating the changelog so that it can commit and push to it.

**Comment by Ocramius** [comment]
Handled in #47
