### ISSUE TITLE
Use CHANGELOG format in releases

### ISSUE THREAD

**Issue by asgrim** [laminas/automatic-releases#5]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | yes
| BC Break    | no

#### Summary

It was mentioned in chat that we should be using `CHANGELOG` format for tag/release descriptions. This needs more work to be implemented, so mainly opening this as a placeholder for intended future implementation.

**Comment by Ocramius** [comment]
If I understand it correctly, we want the tool to add commits to `CHANGELOG.md` here, before pushing a tag.

**Comment by weierophinney** [comment]
The idea would be to use the keep-a-changelog tool to do the following:

- set the release date (`keep-a-changelog version:ready [-r $VERSION]`)
- commit the updated changelog to the release branch
- either use that same tool to create the tag and release, or at least use it to provide the release contents:
  - `keep-a-changelog version:tag <version>` can tag the version, and it inject the changelog into the tag commit message.
  - `keep-a-changelog version:release <version>` will push the tag, and then create the release using the changelog.

Internally, it uses `git -s`, so assuming the GPG keys are setup in the environment, that should work. For creating the release, it has a provider that can take care of that via the API, and it uses its internal functionality to extract the release changelog.

**Comment by weierophinney** [comment]
I've started looking at the code, and there's another option: we install keep-a-changelog as a dependency, and directly use its commands and/or code. We could wrap the `version:ready`, `version:tag`, and `version:release` commands into a single command, or just use the logic to:

- Set the version release date.
- Pull the changelog contents for use with the existing tooling.

Likely this latter approach will introduce less change, and will ensure that the tagging works correctly.
