### ISSUE TITLE
Commit changelog after updating with release date fails, indicating wrong branch is checked out

### ISSUE THREAD

**Issue by weierophinney** [laminas/automatic-releases#51]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.2.2

#### Summary

When issuing a release for laminas-mail, I received an error indicating it could not commit the changelog file back to the release branch, as that branch was not currently selected:

- https://github.com/laminas/laminas-mail/runs/977187215?check_suite_focus=true#step:4:14

#### How to reproduce

Close a milestone, and wait for the action to complete.

#### Expected behavior

If the action is able to read and manipulate the changelog file, it should be able to commit it back to the repo.

**Comment by Ocramius** [comment]
Handled in #55
