### ISSUE TITLE
Randomly not creating next release branch

### ISSUE THREAD

**Issue by weierophinney** [laminas/automatic-releases#74]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | v1 (1.9.0?)

#### Summary

After performing the 2.9.0 release on laminas-paginator, a new release branch was not created (expected 2.10.x creation).

I'm unsure how to reproduce. What may be more useful in addressing this is to add logging wherever we can (particularly since we have a logger available now).

**Comment by lcobucci** [comment]
@weierophinney let's see if the patch I sent fixed this 🤞

**Comment by Ocramius** [comment]
Well, `1.10.x` was correctly created, so I'm closing this one :+1:
